name: Deploy to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4

            -   name: "Clean /testing directory on remote"
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        rm -rf /testing/*
                        mkdir -p /testing

            -   name: "Deploy everything to remote"
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    source: "."
                    target: "/testing"
                    timeout: 60s

            -   name: "Validate NixOS configuration"
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        cd /testing
                        rm -rf .git
                        sudo nixos-rebuild build --flake .#ampere-config
                        if [ $? -eq 0 ]; then
                            echo "Build successful! Proceeding..."
                        else
                            echo "Build failed! Exiting..."
                            exit 1
                        fi
                    timeout: 300s

            -   name: "Generate htpasswd file and give access to Nginx"
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        cd /var/lib/netdata
                        if [ ! -f htpasswd ]; then
                            rm htpasswd
                            sudo htpasswd -c -b htpasswd ${{ secrets.NETDATA_USERNAME }} ${{ secrets.NETDATA_PASSWORD }}
                            sudo chmod 640 htpasswd
                            sudo chown root:nginx htpasswd
                        fi
                    timeout: 60s

            -   name: "Apply NixOS configuration, update Django app and restart services"
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        cd /testing

                        # Install Python dependencies
                        (
                            cd app &&
                            python3 -m venv projectenv &&
                            source projectenv/bin/activate &&
                            pip install -r requirements.txt &&
                            deactivate
                        )

                        # Build frontend
                        (
                            cd app/static/proud &&
                            npm install &&
                            npm run build
                        )

                        # Collect static files
                        (
                            cd app &&
                            source projectenv/bin/activate &&
                            python manage.py collectstatic
                            deactivate
                        )

                        # Apply NixOS config
                        sudo nixos-rebuild switch --flake .#ampere-config

                        # Restart services
                        sudo systemctl restart django-app nginx postgresql
                    timeout: 90s